[workspace]
members = [
    "codegen",
]

[package]
name = "reactive-iui"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[dependencies]
codegen = { path = "codegen", package = "reactive-iui-codegen" }
iui = "0.3.0"
